adopciones/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('apps_adopciones.index.urls', namespace='index')),
    url(r'^mascotas/', include('apps_adopciones.mascota.urls', namespace="mascotas")),
    url(r'^solicitudes/', include('apps_adopciones.adopcion.urls', namespace="solicitudes"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps_adopciones/adopcion/urls.py
from django.conf.urls import url
from apps_adopciones.adopcion.views import solicitudes_create, solicitudes_read_all, solicitudes_update, \
    solicitudes_delete, SolicitudReadAll, SolicitudCreate, SolicitudUpdate, SolicitudDelete, solicitudes_index

urlpatterns = [
    url(r'^$', solicitudes_index, name='solicitudes_index'),
    url(r'^funciones/crear$', solicitudes_create, name='solicitudes_funciones_crear'),
    url(r'^funciones$', solicitudes_read_all, name='solicitudes_funciones'),
    url(r'^funciones/editar/(?P<id_solicitud>\d+)$', solicitudes_update, name='solicitudes_funciones_editar'),
    url(r'^funciones/eliminar/(?P<id_solicitud>\d+)$', solicitudes_delete, name='solicitudes_funciones_eliminar'),
    url(r'^clases/crear$', SolicitudCreate.as_view(), name='solicitudes_clases_crear'),
    url(r'^clases$', SolicitudReadAll.as_view(), name='solicitudes_clases'),
    url(r'^clases/editar/(?P<pk>\d+)$', SolicitudUpdate.as_view(), name='solicitudes_clases_editar'),
    url(r'^clases/eliminar/(?P<pk>\d+)$', SolicitudDelete.as_view(), name='solicitudes_clases_eliminar')
]

apps_adopciones/mascota/urls.py
from django.conf.urls import url

from views import mascotas_create, mascotas_read_all, mascotas_update, mascotas_delete, \
    MascotasReadAll, MascotasCreate, MascotasUpdate, MascotasDelete, mascotas_index

urlpatterns = [
    url(r'^$', mascotas_index, name='mascotas_index'),
    url(r'^funciones/crear$', mascotas_create, name='mascotas_funciones_crear'),
    url(r'^funciones$', mascotas_read_all, name='mascotas_funciones'),
    url(r'^funciones/editar/(?P<id_mascota>\d+)$', mascotas_update, name='mascotas_funciones_editar'),
    url(r'^funciones/eliminar/(?P<id_mascota>\d+)$', mascotas_delete, name='mascotas_funciones_eliminar'),
    url(r'^clases/crear$', MascotasCreate.as_view(), name='mascotas_clases_crear'),
    url(r'^clases$', MascotasReadAll.as_view(), name='mascotas_clases'),
    url(r'^clases/editar/(?P<pk>\d+)$', MascotasUpdate.as_view(), name='mascotas_clases_editar'),
    url(r'^clases/eliminar/(?P<pk>\d+)$', MascotasDelete.as_view(), name='mascotas_clases_eliminar'),
]

templates/index/index.html
{% extends 'base/base.html' %}
{% block content %}
    <div class="h-screen mt-5 flex flex-column gap-3 justify-content-center align-items-center w-100">
        <div class="list-group w-50 mx-auto">
            <a href="{% url 'mascotas:mascotas_funciones' %}"
               class="list-group-item list-group-item-action text-uppercase">
                mascotas funciones
            </a>
            <a href="{% url 'mascotas:mascotas_clases' %}"
               class="list-group-item list-group-item-action text-uppercase">
                mascotas clases
            </a>
            <a href="{% url 'solicitudes:solicitudes_funciones' %}"
               class="list-group-item list-group-item-action text-uppercase">
                solicitudes funciones
            </a>
            <a href="{% url 'solicitudes:solicitudes_clases' %}"
               class="list-group-item list-group-item-action text-uppercase">
                solicitudes clases
            </a>
        </div>
    </div>
{% endblock %}